### ISSUE TITLE
String ID of the action conflicts with the same in DOCX Converter Plugin

### ISSUE THREAD

**Issue by Vitaliy-1** [withanage/typeset#2]
Currently, Typeset Plugin uses the same [Ajax action ID](https://github.com/withanage/typeset/blob/master/TypesetPlugin.inc.php#L95) as DOCX Converter Plugin, thus, replacing the action of the latter if it's enabled or vice versa (depends on their loading order). Could it be changed to something unique?

**Comment by withanage** [comment]
sorry, had  forgotten to replace it when copying.
I have changed it now.
